api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'api'
urlpatterns = [
    #USER
    path('login/', views.loginAPI.as_view(), name='login'),
    path('logout/', views.logoutAPI.as_view(), name='logout'),
    path('registration/', views.registrationAPI.as_view(), name='logout'),
    path('token/', views.tokenAPI.as_view(), name='token'),

    #NAVBAR
    path('navbar/', views.navbarAPI.as_view(),name='navbar'),

    #MANAGER
    path('manager/', views.managerAPI.as_view(), name='manager'),

    #MARKET
    path('market/insert/', views.insertAPI.as_view(), name='insert'),
    path('market/catalog/', views.catalogAPI.as_view(), name='catalog'),
    path('market/user_items/', views.user_itemsAPI.as_view(), name='user_items'),

    path('market/buy_item/', csrf_exempt(views.buyAPI.as_view()), name='buy_item'),
    path('market/remove_item/', views.removeAPI.as_view(), name='remove_item'),

    #COMMUNITY
    path('community/leaderboard/', views.leaderboardAPI.as_view(), name='leaderboard'),
    path('community/profile/<str:username>/', views.profileAPI.as_view(), name='profile'),
    path('community/search_user/', views.searchUserAPI.as_view(), name='search_user'),
    path('community/modify/', views.modifyAPI.as_view(), name='modify'),

    #ANALYTICS
    path('analytics/history/', views.historyAPI.as_view(), name='history'), #GET
    path('analytics/tracker=<str:item>', views.priceTrackerAPI.as_view(), name='price_tracker'), #GET
    path('analytics/search_product/', views.searchProductAPI.as_view(), name='search_product'),
]

community/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'community'
urlpatterns = [
    path('profile/<str:username>', views.community_profile, name = 'community_profile'),
    path('modify/<str:email_error>', views.modify, name='modify'),
    path('modify/', views.modify, name='modify'),
    path('change_profile/', views.change_profile, name='change'),
    path('change_pic/', views.change_pic, name='change_pic'),
    path('search_user/', views.search_user, name ='search_user'),
    path('search/<str:error>', views.search_page, name ='search'),
    path('search/', views.search_page, name ='search'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('',views.index, name = 'index'),
]

martistupe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

#redirection when not found
from django.views.generic import RedirectView


def handler404(request,exception):
    return HttpResponseRedirect(reverse("manager:index"))

#icon
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('analytics/', include('analytics.urls')),
    path('community/', include('community.urls')),
    path('manager/', include('manager.urls')),
    path('market/', include('market.urls')),
    path('', include('user.urls'))
]

community/models.py
from django.db import models

# Create your models here.

community/views.py
from http import HTTPStatus

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse

from manager import models
from user.models import Profile, User, DEFAULT_PIC
from user.forms import ProfileForm
from common import utils

# Create your views here.
@login_required
def index(request):
    template = loader.get_template('community/index.html')
    context = {'balance': utils.get_balance(request)}
    if request.method == 'GET':
        return HttpResponse(template.render(context,request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

@login_required
def leaderboard(request):
    leaderboard = models.Balance.objects.filter().order_by('-balance')

    top10 = leaderboard[:10]
    worse10 = leaderboard.reverse()[:10]

    template = loader.get_template('community/leaderboard.html')
    context = {'balance': utils.get_balance(request), 'leaderboard': leaderboard, 'top10': top10, 'worse10':worse10}
    if request.method == 'GET':
        return HttpResponse(template.render(context,request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

@login_required
def community_profile(request,username):
    template = loader.get_template('community/profile.html')
    if request.method == 'GET':
        try:
            user = User.objects.get(username=username)
            profile = Profile.objects.get(user=user)
            balance = models.Balance.objects.get(user=user)
        except:
            return HttpResponseRedirect(reverse('community:search', args=('User not found',)))
        context = {'balance': utils.get_balance(request), 'user':user,'profile': profile,'profile_balance':balance}

        #your profile page
        if user == request.user:
            context['yourself'] = True
        return HttpResponse(template.render(context,request))
    return HttpResponse('Request not valid', status=HTTPStatus.FOUND)

@login_required
def modify(request,email_error:str=None):
    profile = Profile.objects.get(user=request.user)
    balance = models.Balance.objects.get(user=request.user)
    template = loader.get_template('community/modify.html')
    context = {'balance': utils.get_balance(request), 'profile': profile, 'form': ProfileForm,'profile_balance':balance,'email_error':email_error}
    if request.method == 'GET':
        return HttpResponse(template.render(context,request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

@login_required
def change_profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST)
        if form.is_valid():
            # obtaining arguments
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            mobile = form.cleaned_data['mobile']
            biography = form.cleaned_data['biography']
            user = request.user

            # create new profile associated to the logged
            profile = Profile.objects.get(user=user)
            profile.name = name
            profile.surname = surname
            profile.mobile = mobile
            profile.biography = biography
            user.email = email

            # controlla che tu non abbia inserito la mail di un altro
            try:
                yep = User.objects.get(email=email)
                if (yep.username != user.username):
                    print(yep.username != user.username)
                    error="Email taken by another user, we're sorry"
                    return HttpResponseRedirect(reverse('community:modify', args=(error,)))
                user.save()
                profile.save()  # salvataggio in BACKEND
                return HttpResponseRedirect(reverse('community:community_profile', args=(user.username,)))
            except:
                user.save()
                profile.save()  # salvataggio in BACKEND
                return HttpResponseRedirect(reverse('community:community_profile', args=(user.username,)))
        else:
            """
         Render ricarica la pagina, ma con gli errori
         """
        profile = Profile.objects.get(user=request.user)
        balance = models.Balance.objects.get(user=request.user)
        template = loader.get_template('community/modify.html')

        context = {'balance': utils.get_balance(request), 'profile': profile, 'form': form,
                   'profile_balance': balance}
        return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

    """
    Probabilmente errore nello scrivere, quindi vieni reindirizzato alla pagina giusta
    """
    return HttpResponseRedirect(reverse('community:modify'))

@login_required
def change_pic(request):
    if request.method == 'POST':
        try:
            profile_image = request.FILES['profile_image']
        except:
            profile_image = None

        # create new profile associated to the logged
        profile = Profile.objects.get(user=request.user)
        if profile_image:
            profile.profile_image = profile_image
        else:
            profile.profile_image = DEFAULT_PIC
        profile.save()  # salvataggio in BACKEND
        return HttpResponseRedirect(reverse('community:community_profile', args=(request.user.username,)))
    """
    Probabilmente errore nello scrivere, quindi vieni reindirizzato alla pagina giusta
    """
    return HttpResponseRedirect(reverse('community:modify'))

@login_required
def search_page(request,error:str=None):
    template = loader.get_template('community/search.html')
    context = {'balance': utils.get_balance(request), 'error':error}
    if request.method == 'GET':
        return HttpResponse(template.render(context,request))
    return HttpResponse(template.render(context, request),status=HTTPStatus.FOUND)

@login_required
def search_user(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            if(username):
                try:
                    user = User.objects.get(username=username)
                    return HttpResponseRedirect(reverse('community:community_profile', args=(username,)))
                except:
                    error = 'User not found'
                    return HttpResponseRedirect(reverse('community:search', args=(error,)))
            error = 'You have to type something'
            return HttpResponseRedirect(reverse('community:search', args=(error,)))
        except:
            error = 'No username given'
            return HttpResponseRedirect(reverse('community:search', args=(error,)))
    """
    Probabilmente errore nello scrivere, quindi vieni reindirizzato alla pagina giusta
    """
    return HttpResponseRedirect(reverse('community:search'))

community/templates/community/index.html
{% extends "community_base.html" %}
{% block title %}Index{% endblock %}
{% block index %}
<div id="content">
{% load static %}
    <!-- Breadcrumb Section Begin -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center" style="background-color:	#f7fddb;">
                    <img src="{% static 'community_theme/images/comm.jpg' %}">
                </div>
            </div>
        </div>
    <!-- Breadcrumb Section End -->
<!-- Product Section Begin -->

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="filter__found">
                                    <h6> Visit our community {{ user }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-3 text-center">
            <p>
            <input type="button" id="leaderboard-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="Leaderboard" onclick='explore_button("leaderboard",true,"{% url "community:leaderboard" %}")'></input>
            <input type="button" id="search-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="Search User" onclick='explore_button("search",true,"{% url "community:search" %}")'></input>
            <input type="button" id="profile-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="My profile" onclick='explore_button("profile",true,"{% url "community:community_profile" username=user %}")'></input>
            </p>
        </div>
    </div>
</div>
<br>
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'index');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'none';
        document.getElementById("index").style.display = 'block';
{% endblock %}

community/templates/community/leaderboard.html
{% extends "community_base.html" %}
{% block title %}Index{% endblock %}
{% block leaderboard %}
<div id="content">
{% load static %}
<!-- Leaderboard style -->
<style>
h2{
  text-align: center;
  margin:16px;
}

.avatar {
  vertical-align: middle;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  margin-right: 1em;
}

.table{
  margin-top: 20px;
}

.table thead{
  background:#111;
  color:#fff;
}

.table tr th,.table tr td:nth-child(odd){
text-align:center;
}
</style>

<!-- Product Section Begin -->
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                      <h2>TOP 10</h2>
                      <table id="top10" class="table striped text-center">
                         <thead>
                            <tr>
                                <th>Rank</th>
                                <th>Username</th>
                                <th>Credits</th>
                                <th>Stars</th>
                            </tr>
                         </thead>
                         <tbody>
                         {% for item in top10 %}
                             <tr>
                                 <td>{{forloop.counter}}</td>
                                 <td><a href="{% url 'community:community_profile' username=item.user%}" target="_blank">{{ item.user }}</a></td>
                                 <td>{{item.balance}}</td>
                                 <td>{{item.stars}}</td>
                             </tr>
                         {% endfor %}
                         </tbody>
                      </table>
                </div>
                <div class="col-lg-6">
                         <h2>WORSE 10</h2>
                         <table id="worse10" class="table striped text-center">
                         <thead>
                            <tr>
                                <th>Rank</th>
                                <th>Username</th>
                                <th>Credits</th>
                                <th>Stars</th>
                            </tr>
                         </thead>
                         <tbody>
                         {% for item in worse10 %}
                             <tr>
                                 <td>{{forloop.counter}}</td>
                                 <td><a href="{% url 'community:community_profile' username=item.user%}" target="_blank">{{ item.user }}</a></td>
                                 <td>{{item.balance}}</td>
                                 <td>{{item.stars}}</td>
                             </tr>
                         {% endfor %}
                         </tbody>
                      </table>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row"  height="100px">
                <div class="col-lg-12">
                    <h2>Leaderboard</h2>
                      <table id="fullboard" class="table striped text-center">
                         <thead>
                            <tr>
                                <th>Rank</th>
                                <th>Username</th>
                                <th>Credits</th>
                                <th>Stars</th>
                            </tr>
                         </thead>
                         <tbody>
                         {% for item in leaderboard %}
                             <tr>
                                 <td>{{forloop.counter}}</td>
                                 <td><a href="{% url 'community:community_profile' username=item.user%}" target="_blank">{{ item.user }}</a></td>
                                 <td>{{item.balance}}</td>
                                 <td>{{item.stars}}</td>
                             </tr>
                         {% endfor %}
                         </tbody>
                      </table>
                </div>
            </div>
        </div>
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'leaderboard');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'block';
        document.getElementById("leaderboard").style.display = 'block';
{% endblock %}

community/templates/community/modify.html
{% extends "community_base.html" %}
{% block title %}Modify page{% endblock %}
{% block modify %}
{% if user %}
<div id="content">
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-3 text-center" id="back-profile">
             <input type="button" id="back-profile-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="<< Back to profile" onclick="back_profile_button()"></input>
        </div>
    </div>
</div>
<div class="container" style="margin-top:30px">
    <div class="row my-2">
        <div class="col-lg-9 order-2">
                <div class="" id="profile">
                    <form enctype="multipart/form-data" action="{% url 'community:change' %}" method="post">
                        {% csrf_token %}
                    <div class="row">
                         <div class="input-group input-group-lg">
                        <div class="col-lg-12">
                            <h6>Biography</h6>
                            <p>
                                <input type="text" class="form-control" value="{{profile.biography}}" name="{{form.biography.name}}" required="true" maxlength="400">
                                 {% for error in form.errors %}
                                 {% if error == 'biography' %}
                                    <font color="red">{{form.errors.biography}}</font><br>
                                 {% endif %}
                                 {% endfor %}
                            </p>
                        </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="mt-2"><span class="fa fa-info-circle float-right"></span>Info</h5>
                            <table class="table table-sm table-hover table-striped">
                                <tbody>
                                    <tr>
                                        <td>
                                            <strong>username:</strong> {{user.username}}
                                            <input type="hidden" value="{{user.username}}" name="{{form.username.name}}">
                                            <input type="hidden" value="{{user.password}}" name="{{form.password.name}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>name:</strong> <input type="text" value="{{profile.name}}" required="true" pattern="[a-zA-Z]+" title="Only alphabet chars allowed" name="{{form.name.name}}" maxlength="20">
                                             {% for error in form.errors %}
                                             {% if error == 'name' %}
                                                <font color="red">{{form.errors.name}}</font><br>
                                             {% endif %}
                                             {% endfor %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>surname:</strong> <input type="text" value="{{profile.surname}}" required="true" pattern="[a-zA-Z]+" title="Only alphabet chars allowed" name="{{form.surname.name}}" maxlength="20">
                                             {% for error in form.errors %}
                                             {% if error == 'surname' %}
                                                <font color="red">{{form.errors.surname}}</font><br>
                                             {% endif %}
                                             {% endfor %}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-12">
                            <h5 class="mt-2"><span class="fa fa-id-card float-right"></span>Contacts</h5>
                            <table class="table table-sm table-hover table-striped">
                                <tbody>
                                    <tr>
                                        <td>
                                            <strong>phone:</strong> +39 <input type="text" value="{{profile.mobile}}" required="true" name="{{form.mobile.name}}" pattern="([1-9]{1}[0-9]{9})|([1-9]{1}[0-9]{8})" maxlength="10" minlength="9"  title="Mobile phone must have 9-10 digits">
                                             {% for error in form.errors %}
                                             {% if error == 'mobile' %}
                                                <font color="red">{{form.errors.mobile}}</font><br>
                                             {% endif %}
                                             {% endfor %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>email:</strong> <input type="email" required="true" value="{{user.email}}" name="{{form.email.name}}">
                                             {% for error in form.errors %}
                                             {% if error == 'email' %}
                                                <font color="red">{{form.errors.email}}</font><br>
                                             {% endif %}
                                             {% endfor %}
                                            {% if email_error %}
                                                <p id="my_error" class="error_string">{{email_error}}</p>
                                            {% endif %}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                                        <input name="submit" type="submit" class="form-control" value="Submit" style="background-color: #c9e265; margin-top:10px">
                        </div>
                    </div>
                    </form>
                    <!--/row-->
                </div>
        </div>
        <div class="col-lg-3 text-center align-items-center">
            <h4 class="mb-3 text-center">{{profile.name}} {{profile.surname}}</h4>
            <form enctype="multipart/form-data" action="{% url 'community:change_pic' %}" method="post">
                {% csrf_token %}
            <img src="../../{{profile.profile_image}}" class="mx-auto img-fluid img-circle d-block" alt="avatar" style="height:200px; margin-bottom:20px">
                <div class="input-group">
                        <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" onchange="text()" accept="image/*" name="{{ form.profile_image.name }}" style="width:200px;">
                            <label class="custom-file-label text-left" for="inputGroupFile01">Select profile image</label>
							<script type="application/javascript">
							function text(){
  									var to_change = document.getElementById("label-immagine");
  									var input = document.getElementById("inputGroupFile01").value;
  									if (input.split("\\").pop()) to_change.value = input.split("\\").pop();
  									else to_change.value = "No image uploaded";
							};
							</script>
                        </div>
                    </div>
                <br>
					<input id="label-immagine" type="text" class="form-control" readonly="" value="No image">
                    <br>
                <input name="submit" type="submit" class="form-control" value="Change pic" style="background-color: #c9e265; margin:auto; margin-bottom:10px;">
            </form>
        </div>
    </div>
</div>
{% endif %}
</div>
<script>
        function modify_button() {
            var sections = document.getElementsByTagName("section");
            console.log(sections);
            for (var i = 0; i < sections.length; i++) {
                if(sections[i].id == 'leaderboard');
                else sections[i].style.display = 'none';
            }
            document.getElementById("back").style.display = 'none';
            document.getElementById("modify").style.display = 'block';
            document.getElementById("back-profile").style.display = 'block';
            {% if error %}
            document.getElementById("my_error").innerHTML = '';
            {% endif %}
            processAjaxData("{% url 'community:modify' %}");
        }
        function back_profile_button() {
            var sections = document.getElementsByTagName("section");
            console.log(sections);
            for (var i = 0; i < sections.length; i++) {
                if(sections[i].id == 'leaderboard');
                else sections[i].style.display = 'none';
            }
            document.getElementById("back-profile").style.display = 'none';
            document.getElementById("back").style.display = 'block';
            document.getElementById("profile").style.display = 'block';
            {% if error %}
            document.getElementById("my_error").innerHTML = '';
            {% endif %}
            processAjaxData("{% url 'community:community_profile' username=user %}");
        }
</script>
</div>
{% endblock %}
{% block loaders %}
    loadContent('#profile','{% url 'community:community_profile' username=user %}','#content');
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'modify');
            else sections[i].style.display = 'none';
        }
        document.getElementById("none").style.display = 'block';
        document.getElementById("back-profile").style.display = 'block';
        document.getElementById("modify").style.display = 'block';

        stelline({{profile_balance.user_stars}});
{% endblock %}
{% block more_js %}
        {% if email_error %}
        processAjaxData("{% url 'community:modify' %}");
        {% endif %}
{% endblock %}

community/templates/community/search.html
{% extends "community_base.html" %}
{% block title %}Search{% endblock %}
{% block search %}
<div id="content">
<div class="col-lg-12 text-center mt-5">
  <h3>Search user</h3>
</div>
<div class="col-md-4 offset-md-4 mt-3">
    <form action="{% url 'community:search_user' %}" method="post">
         {% csrf_token %}
<div class="input-group mb-3">
  <input type="text" required="true" class="form-control" placeholder="Enter a valid username.." aria-label="Recipient's username" name="username">
  <div class="input-group-append">
      <button type="submit" class="bg-transparent" style="border:transparent;">
    <span class="input-group-text"><i class="fa fa-search"></i></span>
      </button>
  </div>
  </div>
 </form>
</div>
<br>
</div>
{% endblock %}
{% block more_jquery %}
        document.getElementById("index").style.display = 'none';
        document.getElementById("search").style.display = 'block';
        document.getElementById("leaderboard").style.display = 'none';
        document.getElementById("back").style.display = 'block';
        document.getElementById("profile").style.display = 'none';
        document.getElementById("modify").style.display = 'none';
{% endblock %}
{% block more_js %}
        {% if error %}
        processAjaxData("{% url 'community:search' %}");
        {% endif %}
{% endblock %}