api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'api'
urlpatterns = [
    #USER
    path('login/', views.loginAPI.as_view(), name='login'),
    path('logout/', views.logoutAPI.as_view(), name='logout'),
    path('registration/', views.registrationAPI.as_view(), name='logout'),
    path('token/', views.tokenAPI.as_view(), name='token'),

    #NAVBAR
    path('navbar/', views.navbarAPI.as_view(),name='navbar'),

    #MANAGER
    path('manager/', views.managerAPI.as_view(), name='manager'),

    #MARKET
    path('market/insert/', views.insertAPI.as_view(), name='insert'),
    path('market/catalog/', views.catalogAPI.as_view(), name='catalog'),
    path('market/user_items/', views.user_itemsAPI.as_view(), name='user_items'),

    path('market/buy_item/', csrf_exempt(views.buyAPI.as_view()), name='buy_item'),
    path('market/remove_item/', views.removeAPI.as_view(), name='remove_item'),

    #COMMUNITY
    path('community/leaderboard/', views.leaderboardAPI.as_view(), name='leaderboard'),
    path('community/profile/<str:username>/', views.profileAPI.as_view(), name='profile'),
    path('community/search_user/', views.searchUserAPI.as_view(), name='search_user'),
    path('community/modify/', views.modifyAPI.as_view(), name='modify'),

    #ANALYTICS
    path('analytics/history/', views.historyAPI.as_view(), name='history'), #GET
    path('analytics/tracker=<str:item>', views.priceTrackerAPI.as_view(), name='price_tracker'), #GET
    path('analytics/search_product/', views.searchProductAPI.as_view(), name='search_product'),
]

martistupe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

#redirection when not found
from django.views.generic import RedirectView


def handler404(request,exception):
    return HttpResponseRedirect(reverse("manager:index"))

#icon
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('analytics/', include('analytics.urls')),
    path('community/', include('community.urls')),
    path('manager/', include('manager.urls')),
    path('market/', include('market.urls')),
    path('', include('user.urls'))
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'user'
urlpatterns = [
    path('execute_login/', views.execute_login, name='enter'),
    path('registration/', views.registration, name='registration'),
    path('execute_registration/', views.execute_registration, name='complete'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.user_login, name='login')
]

user/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator, DecimalValidator
from django.db import models
# Create your models here.
from django.db.models import ImageField

DEFAULT_PIC = "static/profile_pics/default-avatar.jpg"
PROFILE_PIC = "static/profile_pics/"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    mobile = models.IntegerField()
    biography = models.CharField(max_length=400)
    profile_image = ImageField(upload_to=PROFILE_PIC, blank=True, default=DEFAULT_PIC)


    def __str__(self):
        return f'Profile of {self.user}'

user/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.forms import ModelForm
from user.models import Profile


class ProfileForm(ModelForm):
    username = forms.CharField(label='Enter your username')
    email = forms.CharField(label='Enter your email',validators=[EmailValidator(message='Not a valid email address')])
    password = forms.CharField(label='Enter your password', widget=forms.PasswordInput())
    class Meta:
        model = Profile
        fields = ['username', 'email', 'password','name', 'surname', 'mobile', 'biography', 'profile_image']

    def clean_username(self):
        data = self.cleaned_data
        username = data['username']
        if len(username) > 10:
            raise forms.ValidationError(('10 characters max'), code='user_limit')
        return username

    def clean_name(self):
        data = self.cleaned_data
        name = data['name']
        if not re.fullmatch('[a-zA-Z]+', name):
            raise forms.ValidationError(("You can't have special characters in your name, unless you're Musk"), code='name_number')
        return name

    def clean_surname(self):
        data = self.cleaned_data
        surname = data['surname']
        if not re.fullmatch('[a-zA-Z]+', surname):
            raise forms.ValidationError(("You can't have special characters in your name, unless you're Musk"), code='surname_number')
        return surname

    def clean_mobile(self):
        data = self.cleaned_data
        mobile = data['mobile']
        phone = str(mobile)
        if len(phone) > 10 or len(phone) < 9:
            raise forms.ValidationError(('Not a valid phone number'), code='phone')
        return mobile

    def clean_profile_image(self):
        data = self.cleaned_data
        profile_image = data['profile_image']
        return profile_image

class LoginForm(forms.Form):
    username = forms.CharField(label='Enter your username')
    password = forms.CharField(label='Enter your password', widget=forms.PasswordInput())

user/views.py
from http import HTTPStatus

from django.core import mail
from django.core.mail import send_mail
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.db.models import Q

from martistupe import settings
from . import forms, models
from common import utils

def user_logout(request):
    logout(request)
    if request.method == 'GET':
        return HttpResponseRedirect(reverse('user:login'))
    return HttpResponseRedirect(reverse('user:login'), status=HTTPStatus.FOUND)

def user_login(request):
    #if user is authenticated he can't possibly acces this page!
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('manager:index'))
    template = loader.get_template('user/login.html')
    context = {'form': forms.LoginForm}
    if request.method == 'GET':
        return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

def execute_login(request):
    # if user is authenticated he can't possibly acces this page!
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('manager:index'))
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            #obtaining arguments
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #authenticate
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                # log the user in!
                login(request,user)
                return HttpResponseRedirect(reverse('manager:index'))
            error = 'Wrong username or password.'
            return render(request, 'user/login.html', {'form': form, 'error':error}, status=HTTPStatus.FOUND)
        """
        Se qualche dato è stato inserito in maniera non corretta, si ritorna alla schermata di login
        """
        error = 'Invalid data.'
        return render(request, 'user/login.html', {'form': form, 'error':error}, status=HTTPStatus.FOUND)
    """
    Se il metodo con cui è stata chiamata questa funzione non è post, qualcosa non è andato correttamente
    Si ritorna quindi alla schermata di login
    """
    return HttpResponseRedirect(reverse('user:login'), status=HTTPStatus.FOUND)

def registration(request):
    # if user is authenticated he can't possibly acces this page!
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('manager:index'))
    template = loader.get_template('user/register.html')
    context = {'form': forms.ProfileForm}
    if request.method == 'GET':
        return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

def execute_registration(request):
    # if user is authenticated he can't possibly acces this page!
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('manager:index'))
    if request.method == 'POST':
        form = forms.ProfileForm(data=request.POST)
        if form.is_valid():
            #obtaining arguments
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            name =  form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            mobile = form.cleaned_data['mobile']
            biography = form.cleaned_data['biography']
            #UPLOADED IMAGE
            try:
                profile_image = request.FILES['profile_image']
            except:
                profile_image = None
            """if profile_image: #if inserted, add default folder
                profile_image = models.PROFILE_PIC + profile_image
            if not profile_image: #else, equal to default pic
                profile_image = models.DEFAULT_PIC"""
            """
            Controlla se le informazioni inserite sono già occupate
            - se email e username sono già in uso
            - se o username o email sono già in uso
            nel caso stampa l'errore
            """
            if User.objects.filter(Q(username = username) | Q(email = email)):
                error = 'Username or email already in use.'
                return render(request, 'user/register.html', {'form': form, 'error':error}, status=HTTPStatus.FOUND)

            utils.send_html_mail(
                subject='Welcome to our community!',
                recipient_list=[email],
                html_content=f"""
                <html>
                    <head></head>
                  <body>
                    <p>
                       Congratulation {username}, the registration was successful. Go visit our market!<br> 
                       <a href="http://{request.get_host()}/market">Click here</a>
                    </p>
                  </body>
                </html>
                """,
                fail_silently=True
            )

            #create new user
            user = User.objects.create_user(username, email)
            user.set_password(password)

            user.save() #salvataggio in BACKEND

            #create new profile associated with that user
            if profile_image:
                profile = models.Profile(user=user,name=name,surname=surname,mobile=mobile,biography=biography,profile_image=profile_image)
            else:
                profile = models.Profile(user=user,name=name,surname=surname,mobile=mobile,biography=biography)
            profile.save() #salvataggio in BACKEND

            # log the new user in!
            login(request, authenticate(username=username, password=password))

            return HttpResponseRedirect(reverse('manager:index'))
        else:
            """
            Render ricarica la pagina, ma con gli errori
            """
            return render(request, 'user/register.html', {'form': form}, status=HTTPStatus.FOUND)
    """
      Se il metodo con cui è stata chiamata questa funzione non è post, qualcosa non è andato correttamente
      Si ritorna quindi alla schermata di registrazione
    """
    return HttpResponseRedirect(reverse('user:registration'))

user/templates/user/login.html
{% extends "user_base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'user:enter' %}" method="post">
                    {% csrf_token %}
					<span class="login100-form-title p-b-43">
						Login to continue
					</span>

					{% if error  %}
						<font color="red">{{error}}</font><br><br>
					{% endif %}
                    {% for field in form  %}
					{% if field.name|stringformat:"s" == "password" %}
					<div class="wrap-input100">
						<input class="input100" type="password" required="true" name="{{ field.name }}">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% else %}
					<div class="wrap-input100">
						<input class="input100" type="text" required="true" name="{{ field.name }}">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% endif %}
                    {% endfor %}

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn" style="background-color:#c9e265;">
							Login
						</button>
					</div>

					<div class="text-center p-t-46 p-b-20">
						<span class="txt2">
                            or <a href="{% url 'user:registration' %}"> Sign up!</a>
						</span>
					</div>
				</form>

				<div class="login100-more" style="background-image: url({% static 'login_theme/images/b-02.jpg' %}); ">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

user/templates/user/register.html
{% extends "user_base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" enctype="multipart/form-data" action="{% url 'user:complete' %}" method="post">
                    {% csrf_token %}
					<span class="login100-form-title p-b-43">
						Complete registration:
					</span>

                    {% if error %}
                        <font color="red">{{error}}</font>
                    {% endif %}
                    {% for field in form  %}
                    {% for error in field.errors %}
                    <font color="red">{{error}}</font><br>
                    {% endfor %}
                    {% if field.name|stringformat:"s" == "password" %}
					<div class="wrap-input100">
						<input class="input100" required="true" type="password" name="{{ field.name }}">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
                    {% elif field.name|stringformat:"s" == "profile_image" %}
                    <br>
                    <div class="input-group">
                        <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" onchange="text()" accept="image/*" name="{{ field.name }}" >
                            <label class="custom-file-label" for="inputGroupFile01">Select profile image</label>
							<script type="application/javascript">
							function text(){
  									var to_change = document.getElementById("label-immagine");
  									var input = document.getElementById("inputGroupFile01").value;
  									if (input.split("\\").pop()) to_change.value = input.split("\\").pop();
  									else to_change.value = "No image uploaded";
							};
							</script>
                        </div>
                    </div>
					<br>
					<input id="label-immagine" type="text" class="form-control" readonly="" value="No image">
                    <br>
					{% elif field.name|stringformat:"s" == "email" %}
					<div class="wrap-input100">
						<input class="input100" type="email" required="true" name="{{ field.name }}">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% elif field.name|stringformat:"s" == "username" %}
					<div class="wrap-input100">
						<input class="input100" type="text" required="true" name="{{ field.name }}" maxlength="10">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% elif field.name|stringformat:"s" == "name"%}
					<div class="wrap-input100">
						<input class="input100" type="text" required="true" pattern="[a-zA-Z]+" title="Only alphabet chars allowed" name="{{ field.name }}" maxlength="20">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% elif field.name|stringformat:"s" == "surname"%}
					<div class="wrap-input100">
						<input class="input100" type="text" required="true" pattern="[a-zA-Z]+" title="Only alphabet chars allowed" name="{{ field.name }}" maxlength="20">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
					{% elif field.name|stringformat:"s" == "mobile"%}
					<div class="wrap-input100">
						<input class="input100" type="tel" required="true" name="{{ field.name }}" pattern="([1-9]{1}[0-9]{9})|([1-9]{1}[0-9]{8})" maxlength="10" minlength="9"  title="Mobile phone must have 9-10 digits">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
                    {% else %}
					<div class="wrap-input100">
						<input class="input100" type="text" required="true" name="{{ field.name }}">
						<span class="focus-input100"></span>
						<span class="label-input100">{{ field.label_tag }}</span>
					</div>
                    {% endif %}
                    {% endfor %}

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn" style="background-color:#c9e265;">
							Register
						</button>
					</div>

					<div class="text-center p-t-46 p-b-20">
						<span class="txt2">
                            or <a href="{% url 'user:login' %}"> Sign in!</a>
						</span>
					</div>
				</form>

				<div class="login100-more" style="background-image: url({% static 'login_theme/images/b-02.jpg' %}); ">
				</div>
			</div>
		</div>
	</div>
{% endblock %}