analytics/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'analytics'
urlpatterns = [
    path('history', views.history, name='history'),
    path('tracker=<str:item>', views.price_tracker, name='price_tracker'),
    path('search_product/', views.search_product, name='search_product'),
    path('search/<str:error>', views.search_page, name='search'),
    path('search/', views.search_page, name='search'),
    path('',views.index, name = 'index'),
]

api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'api'
urlpatterns = [
    #USER
    path('login/', views.loginAPI.as_view(), name='login'),
    path('logout/', views.logoutAPI.as_view(), name='logout'),
    path('registration/', views.registrationAPI.as_view(), name='logout'),
    path('token/', views.tokenAPI.as_view(), name='token'),

    #NAVBAR
    path('navbar/', views.navbarAPI.as_view(),name='navbar'),

    #MANAGER
    path('manager/', views.managerAPI.as_view(), name='manager'),

    #MARKET
    path('market/insert/', views.insertAPI.as_view(), name='insert'),
    path('market/catalog/', views.catalogAPI.as_view(), name='catalog'),
    path('market/user_items/', views.user_itemsAPI.as_view(), name='user_items'),

    path('market/buy_item/', csrf_exempt(views.buyAPI.as_view()), name='buy_item'),
    path('market/remove_item/', views.removeAPI.as_view(), name='remove_item'),

    #COMMUNITY
    path('community/leaderboard/', views.leaderboardAPI.as_view(), name='leaderboard'),
    path('community/profile/<str:username>/', views.profileAPI.as_view(), name='profile'),
    path('community/search_user/', views.searchUserAPI.as_view(), name='search_user'),
    path('community/modify/', views.modifyAPI.as_view(), name='modify'),

    #ANALYTICS
    path('analytics/history/', views.historyAPI.as_view(), name='history'), #GET
    path('analytics/tracker=<str:item>', views.priceTrackerAPI.as_view(), name='price_tracker'), #GET
    path('analytics/search_product/', views.searchProductAPI.as_view(), name='search_product'),
]

community/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'community'
urlpatterns = [
    path('profile/<str:username>', views.community_profile, name = 'community_profile'),
    path('modify/<str:email_error>', views.modify, name='modify'),
    path('modify/', views.modify, name='modify'),
    path('change_profile/', views.change_profile, name='change'),
    path('change_pic/', views.change_pic, name='change_pic'),
    path('search_user/', views.search_user, name ='search_user'),
    path('search/<str:error>', views.search_page, name ='search'),
    path('search/', views.search_page, name ='search'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('',views.index, name = 'index'),
]

market/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'market'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert', views.insert, name='insert'),
    path('catalog/<str:error>', views.catalog, name='catalog'),
    path('catalog', views.catalog, name='catalog'),
    path('user_items/<str:error>', views.user_items, name='user_items'),
    path('user_items', views.user_items, name='user_items'),
    path('add_item', views.add_item, name='add_item'),
    path('buy_item', views.buy_item, name='buy_item'),
    path('remove_item', views.remove_item, name='remove_item')
]

martistupe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

#redirection when not found
from django.views.generic import RedirectView


def handler404(request,exception):
    return HttpResponseRedirect(reverse("manager:index"))

#icon
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('analytics/', include('analytics.urls')),
    path('community/', include('community.urls')),
    path('manager/', include('manager.urls')),
    path('market/', include('market.urls')),
    path('', include('user.urls'))
]

market/models.py
from django.db import models

# Create your models here.

market/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
#verrò cambiato se definisco un profilo utente
from django.contrib.auth.models import User
from django.db.models import Q
from http import HTTPStatus
from manager import forms,models
from common import utils

# Create your views here.
from martistupe import settings


@login_required
def index(request):
    template = loader.get_template('market/index.html')
    context = {'balance': utils.get_balance(request), }
    if request.method == 'GET':
        return HttpResponse(template.render(context,request))
    return HttpResponse(template.render(context,request), status=HTTPStatus.FOUND)

@login_required
def insert(request):
    template = loader.get_template('market/insert.html')
    context = {'balance': utils.get_balance(request),'catalog_form': forms.InsertCatalogForm(prefix='catalog'), 'product_form': forms.ProductForm(prefix='product')}
    if request.method == 'GET':
        return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request),status=HTTPStatus.FOUND)

@login_required
def catalog(request,error:str=None):
    template = loader.get_template('market/catalog.html')

    user = request.user
    catalog = models.Catalog.objects.filter(~Q(user = user)) #mostra solo ciò che vendono gli altri!
    """
    A partire dalla lista di elementi del catalogo, genero un insieme di gruppi:
    - la "key" di ogni gruppo è il nome del prodotto
    - il "items" di ogni gruppo è la lista di "vendite" di quel prodotto
    - "count" è un conteggio di quanti item ci sono
    
    ATTENZIONE: si parte dal presupposto che non ci siano prodotti con lo stesso nome
    """

    #GENERO LE CHIAVI, non duplicate e ordinate
    keys = {item.product.name for item in catalog}    #un set rimuove i duplicati da solo
    keys = sorted(keys) #ordino
    #Trasformo il catalogo in una lista da QuerySet
    values = [item for item in catalog]

    #Genero l'insieme di "gruppi", come indicato sopra
    groups = []
    for key in keys:
        new_dict = {}
        new_dict['key'] = key
        new_dict['items'] = []
        for item in values:
            #add value if key correspond
            if item.product.name == key:
                new_dict['items'].append(item)
        new_dict['items']= sorted(new_dict['items'], key=lambda item: (item.price,item.quantity))
        new_dict['count'] = len(new_dict['items'])
        groups.append(new_dict)

    context = {'balance': utils.get_balance(request),'groups': groups,'error':error, 'product_number': len(catalog)}
    if request.method == 'GET':
        return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

@login_required
def user_items(request, error:str=None):
    """
    Stampa i tuoi annunci attualmente attivi (la roba che hai venduto non ancora comprata)
    :param request:
    :return:
    """
    template = loader.get_template('market/user_items.html')

    catalog = models.Catalog.objects.filter(user=request.user)  # mostra solo ciò che vendono gli altri!
    #BACKEND ^

    context = {'balance': utils.get_balance(request),'catalog': catalog, 'error':error}
    if request.method == 'GET':
        return HttpResponse(template.render(context, request))
    return HttpResponse(template.render(context, request), status=HTTPStatus.FOUND)

@login_required
def add_item(request):
    if request.method == 'POST':
        product_form = forms.ProductForm(request.POST, prefix='product')
        catalog_form = forms.InsertCatalogForm(request.POST,prefix='catalog')
        if product_form.is_valid() and catalog_form.is_valid():
            #recovering parameters, after validation
            name = product_form.cleaned_data['name']
            price = catalog_form.cleaned_data['price']
            category = product_form.cleaned_data['category']
            quantity = catalog_form.cleaned_data['quantity']
            #search an object from exsisting ones (can't create new category for now) to be assigned to your new product
            try:
                category_obj = models.Category.objects.get(name = category)
            except:
                return HttpResponseRedirect(reverse('market:insert'))


            #capitalize all name to avoid duplicates
            name = name.capitalize()
            #search for the product
            product = models.Product.objects.filter(name=name).first()
            if(not product):
                #create new product if it doesn't exists
                product = models.Product(name = name, category = category_obj)
                product.save()
            #CONTROLLO SE L'UTENTE HA GIà INSERITO LO STESSO PRODOTTO IN PASSATO: nel caso aggiorno quantitò e prezzo
            item = models.Catalog.objects.filter(user = request.user, product = product).first()
            if (item):
                item.price = float(price)   #aggiorno il prezzo prendendo quello nuovo
                item.quantity = int(quantity) + item.quantity   #aggiorno la quantità sommandole
                item.save()
            else:
                print(product)
                #create a new entry in the catalog associated to that product, and to the current logged user
                new_item = models.Catalog(quantity=quantity, product=product, user = request.user, price=price)
                new_item.save()

            return HttpResponseRedirect(reverse('market:user_items'))
        else:
            """
            Printa la pagina con gli errori del form
            """
            return render(request, 'market/insert.html', {'balance': utils.get_balance(request),'product_form': product_form, 'catalog_form':catalog_form}, status=HTTPStatus.FOUND)
    """
    Se il metodo con cui è stata chiamata questa funzione non è post, qualcosa non è andato correttamente
    Si ritorna quindi alla schermata di registrazione
    """
    return HttpResponseRedirect(reverse('market:insert'))

@login_required
def buy_item(request):
    """
    This page receive a post request from "catalog" and after processing it, redirect into your index
    :return: redirect in index page (can be changed into a catalog)
    """
    if request.method == 'POST':
        #Recupero la quantità in input e l'id dell'item del catalogo
        try:
            quantity = request.POST['quantity']
            item_id = request.POST['item_id']
        except:
            error = "Something wrong with your request."
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))
        try:
            item = models.Catalog.objects.get(id=item_id)
        except:
            error = "Couldn't find the item requested in catalog."
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))

        #se funzia, recupero i vari campi dell'item
        product_name = item.product.name
        product_category = item.product.category
        seller = item.user
        price = item.price
        max_quantity = item.quantity

        #ERRORS!
        #controllo che esistano prodotto e venditore
        if (int(quantity) > int(max_quantity)):
            error = "You tried to buy, but we don't have that much!"
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))
        seller = User.objects.get(username=seller)
        if (not seller):  # se è a null qualcosa è andato male
            error = "Couldn't find user associated with this item in the catalog, try again or buy from someone else."
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))
        product = models.Product.objects.get(name=product_name, category=product_category)
        if (not product):  # se è a null vuol dire che qualcosa è andato male
            error = "Couldn't find the product associated with your request, try again or try to buy something else."
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))

        #define what i spent with this trade
        amount = float(quantity) * float(price)

        """
        Operazione di acquisto
        - recupero l'utente acquirente
        - recupero il suo balance, e lo aggiorno
        - aggiungo una nuova transizione per l'utente, con ammontare negativo
        """
        buyer = request.user #save current user
        #non controllo se esiste, perchè qui ci arrivo solo se ho fatto il login!
        buyer_balance = models.Balance.objects.get(user=buyer)    #find his balance

        #CONTROLLO BUDGET UTENTE
        if (float(buyer_balance.balance) - amount < (-1)*(models.BALANCE_LIMIT)):
            error = "You don't have enough credits (limit reached)."
            return HttpResponseRedirect(reverse('market:catalog', args=(error,)))

        # non controllo se l'ha trovato o meno: ogni utente registrato ha un suo balance, se non ce l'avesse non troverei neanche l'utente!
        buyer_balance.balance = float(buyer_balance.balance) - amount     #update his balance
        buyer_balance.save()

        #save the transaction, price is negative cause it's a buy and not a sell
        new_entry = models.Transaction(product=product, user=buyer, amount=-amount)
        new_entry.save()

        """
        Operazione di vendita
        - recupero dalla post l'utente venditore
        - recupero il suo balance, e lo aggiorno
        - aggiungo una transazione per chi compra
        """
        seller_balance = models.Balance.objects.get(user=seller)  # find his balance
        #non controllo se l'ha trovato o meno: ogni utente registrato ha un suo balance, se non ce l'avesse non troverei neanche l'utente!

market/templates/market/catalog.html
{% extends "market_base.html" %}
{% block head %}
{% endblock %}
{% block title %}Catalog{% endblock %}
{% block catalog %}
<div id="content">
<style>
    h2{
  text-align: center;
  margin:16px;
}
</style>

<!-- Starting of ajax contact form -->
<div class="container">
  <h2>Consult the catalog</h2>
</div>

    <!-- Product Section Begin -->

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="filter__found">
                                    <h6><span>{{product_number}} PRODUCTS FOR SALE</span></h6>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
                        {% for group in groups  %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="filter__found">
                                    <h6><span>{{group.key}} ({{group.count}})</span> <i id="{{group.key}}_hide" class="fa fa-caret-square-o-up" onclick="collapse({{group.key}})" style="positio:relative;bottom:-50px;"></i></h6>
                                </div>
                                <div class="price_track">
                                    <a href="{% url 'analytics:price_tracker' item=group.key %}" target="_blank">Price tracker</a>
                                </div>
                            </div>
                        </div>
                        <div class="row" id="{{group.key}}">
                        <!--{{group.key}} ({{group.count}})
                            <li><a href="{% url 'analytics:price_tracker' item=group.key %}" target="_blank">Price tracker</a></li>-->
                            {% for item in group.items %}
                            {% if item.product.name == group.key %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <form action="{% url 'market:buy_item' %}" method="post">
                                    {% csrf_token %}
                                        <div class="product__item">
                                            <ul class="product__item__pic__hover">
                                                    <li><p><i class="fa fa-plus" onclick="increment('{{forloop.parentloop.counter}}_{{forloop.counter}}')"></i></p></li>
                                                    <li><p><i class="fa fa-minus" onclick="decrement('{{forloop.parentloop.counter}}_{{forloop.counter}}')"></i></p></li>
                                                    <li><button type="submit"><p><i class="fa fa-shopping-cart"></i></p></button></li>
                                            </ul>
                                            <div class="product__item__text">
                                                <h6>{{ item.product.name }}</h6>
                                                <h5>${{item.price}}</h5>
                                                <h6>{{ item.date }}</h6>
                                                <h6>Quantity <input type="text" id="{{forloop.parentloop.counter}}_{{forloop.counter}}" name="quantity" value=1 style="background: transparent;
    border: none; width:16px;" readonly> [max {{item.quantity}}]</h6>
                                                <h6>Sold by <a href="{% url 'community:community_profile' username=item.user%}" target="_blank">{{ item.user }}</a> </h6>
                                            </div>
                                        </div>
                                    <input type="hidden" name="item_id" value={{item.id}}>
                                    <!-- necessario se si vuole usare i bottono + e - -->
                                    <input type="hidden" id="max_quantity{{forloop.parentloop.counter}}_{{forloop.counter}}" name="max_quantity" value={{item.quantity}}>
                                </form>
                            </div>
                            {% endif %}
                            {% endfor %}
                  </div>
                 {% endfor %}
        </div>

    <!-- Product Section End -->
</div>
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'catalog');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'block';
        document.getElementById("catalog").style.display = 'block';
{% endblock %}
{% block more_js %}
        {% if error %}
        processAjaxData("{% url 'market:catalog' %}");
        {% endif %}
{% endblock %}

market/templates/market/index.html
{% extends "market_base.html" %}
{% block title %}Index{% endblock %}
{% block index %}
<div id="content">
{% load static %}
    <!-- Breadcrumb Section Begin -->
        <div class="container" id="logo">
            <div class="row">
                <div class="col-lg-12 text-center" style="background-color:	#f7fddb;">
                    <img src="{% static 'shop_theme/img/banner.jpg' %}">
                </div>
            </div>
        </div>

    <!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="filter__found">
                                    <h6> {{ user }} consult the catalog and sell your items</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-3 text-center">
            <p>
            <input type="button" id="explore-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="Explore Catalog" onclick='explore_button("catalog",true,"{% url "market:catalog" %}")'></input></a>
            <input type="button" id="insert-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="Insert New Item" onclick='explore_button("insert",true,"{% url "market:insert" %}")'></input>
            <input type="button" id="check-button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="Check Your Items" onclick='explore_button("user_items",true,"{% url "market:user_items" %}")'></input>
            </p>
        </div>
    </div>
</div>




<br>
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'index');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'none';
        document.getElementById("index").style.display = 'block';
{% endblock %}

market/templates/market/insert.html
    <!-- Element of the ajax contact form -->{% extends "market_base.html" %}
{% block title %}Insert{% endblock %}
{% block insert %}
<div id="content">
<style>
    h2{
  text-align: center;
  margin:16px;
}
</style>

<!-- Starting of ajax contact form -->
<div class="container">
  <h2>Insert your product</h2>
</div>
<div class="container">
<form class="contact__form container" method="post" action="{% url 'market:add_item' %}">
    {% csrf_token %}

    <!-- Element of the ajax contact form -->
    <div class="row">
        {% for field in product_form  %}
            {% for error in field.errors %}
                    <p class="error_string">{{error}}</p>
            {% endfor %}
            <div class="col-md-6 form-group">
                {{field.label_tag}}
                {{field}}
            </div>
        {% endfor %}
        {% for field in catalog_form  %}
            {% for error in field.errors %}
                    <p class="error_string">{{error}}</p>
            {% endfor %}
            <div class="col-md-6 form-group">
                 {{field.label_tag}}
                 {{field}}
            </div>
        {% endfor %}
        <div class="col-12">
            <input name="submit" type="submit" class="form-control" value="Insert" style="background-color: #c9e265; margin-top:10px; margin-bottom:30px;">
        </div>
    </div>
</form>
</div>
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'insert');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'block';
        document.getElementById("insert").style.display = 'block';
{% endblock %}

market/templates/market/success.html
{% extends "market_base.html" %}
{% block title %}Success{% endblock %}
{% block success %}
{% load static %}
<script type="text/javascript" src="{% static 'shop_theme/js/catalog.js' %}"></script>

<div id="index">
</div>
<div id="insert">

</div>
<div id="catalog">

</div>
<div id="user_items">

</div>
<div id="success">
    <!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4 mt-3 text-center">
                                <div class="filter__found">
                                    <h6 style="margin-bottom:20px;"> <span>{{ user }}, your transaction was successful!</span></h6>
                                </div>
                </div>
            </div>
        </div>


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-3 text-center">
            <table class="table table-sm table-hover table-striped">
                <tbody>
                    <tr>
                        <td>
                            <strong><b>Product</b>: </strong> {{product}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><b>Quantity</b>: </strong> {{quantity}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><b><b>Price</b>: </b></strong> {{price}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><b><b>Total</b>: </b></strong> {{amount}} credits.
                        </td>
                    </tr>
                </tbody>
            </table>
             <input type="button" id="success_button" class="btn btn-block" style="background-color: #c9e265; margin:1px;" value="<< Back to catalog" onclick='back_success_button("catalog",true,"{% url "market:catalog" %}")'></input>
    </div>
</div>
        </div>
    </div>
</div>
<br>
</div>
{% endblock %}
{% block loaders %}
    $( "#catalog" ).load("{% url 'market:catalog' %} #content" );
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'success');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'none';
        document.getElementById("success").style.display = 'block';
{% endblock %}

market/templates/market/user_items.html
{% extends "market_base.html" %}
{% block title %}Your items to be sold{% endblock %}
{% block user_items %}
<div id="content">
<style>
    h2{
  text-align: center;
  margin:16px;
}
</style>

<div class="container">
  <h2>Your products</h2>
</div>
    <!-- Product Section Begin -->

        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="filter__found">
                                    {% if not catalog %}
                                    <h6>No product found..</h6>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                        <div class="row">
                            {% for item in catalog %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <form action="{% url 'market:remove_item' %}" method="post">
                                    {% csrf_token %}
                                        <div class="product__item">
                                            <ul class="product__item__pic__hover">
                                                    <li><button type="submit"><p><i class="fa fa-remove"></i></p></button></li>
                                            </ul>
                                            <div class="product__item__text">
                                                <h6>{{ item.product.name }}</h6>
                                                <h5>${{item.price}}</h5>
                                                <h6>{{ item.date }}</h6>
                                                <h6>Quantity: {{item.quantity}}</h6>
                                            </div>
                                        </div>
                                    <input type="hidden" name="item_id" value={{item.id}}>
                                </form>
                            </div>
                            {% endfor %}
                  </div>
        </div>
    </section>
    <!-- Product Section End -->
</div>
{% endblock %}
{% block more_jquery %}
        var sections = document.getElementsByTagName("section");
        console.log(sections);
        for (var i = 0; i < sections.length; i++) {
            if(sections[i].id == 'user_items');
            else sections[i].style.display = 'none';
        }
        document.getElementById("back").style.display = 'block';
        document.getElementById("user_items").style.display = 'block';
{% endblock %}

{% block more_js %}
        {% if error %}
        processAjaxData("{% url 'market:user_items' %}");
        {% endif %}
{% endblock %}