analytics/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'analytics'
urlpatterns = [
    path('history', views.history, name='history'),
    path('tracker=<str:item>', views.price_tracker, name='price_tracker'),
    path('search_product/', views.search_product, name='search_product'),
    path('search/<str:error>', views.search_page, name='search'),
    path('search/', views.search_page, name='search'),
    path('',views.index, name = 'index'),
]

api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'api'
urlpatterns = [
    #USER
    path('login/', views.loginAPI.as_view(), name='login'),
    path('logout/', views.logoutAPI.as_view(), name='logout'),
    path('registration/', views.registrationAPI.as_view(), name='logout'),
    path('token/', views.tokenAPI.as_view(), name='token'),

    #NAVBAR
    path('navbar/', views.navbarAPI.as_view(),name='navbar'),

    #MANAGER
    path('manager/', views.managerAPI.as_view(), name='manager'),

    #MARKET
    path('market/insert/', views.insertAPI.as_view(), name='insert'),
    path('market/catalog/', views.catalogAPI.as_view(), name='catalog'),
    path('market/user_items/', views.user_itemsAPI.as_view(), name='user_items'),

    path('market/buy_item/', csrf_exempt(views.buyAPI.as_view()), name='buy_item'),
    path('market/remove_item/', views.removeAPI.as_view(), name='remove_item'),

    #COMMUNITY
    path('community/leaderboard/', views.leaderboardAPI.as_view(), name='leaderboard'),
    path('community/profile/<str:username>/', views.profileAPI.as_view(), name='profile'),
    path('community/search_user/', views.searchUserAPI.as_view(), name='search_user'),
    path('community/modify/', views.modifyAPI.as_view(), name='modify'),

    #ANALYTICS
    path('analytics/history/', views.historyAPI.as_view(), name='history'), #GET
    path('analytics/tracker=<str:item>', views.priceTrackerAPI.as_view(), name='price_tracker'), #GET
    path('analytics/search_product/', views.searchProductAPI.as_view(), name='search_product'),
]

community/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'community'
urlpatterns = [
    path('profile/<str:username>', views.community_profile, name = 'community_profile'),
    path('modify/<str:email_error>', views.modify, name='modify'),
    path('modify/', views.modify, name='modify'),
    path('change_profile/', views.change_profile, name='change'),
    path('change_pic/', views.change_pic, name='change_pic'),
    path('search_user/', views.search_user, name ='search_user'),
    path('search/<str:error>', views.search_page, name ='search'),
    path('search/', views.search_page, name ='search'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('',views.index, name = 'index'),
]

market/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'market'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert', views.insert, name='insert'),
    path('catalog/<str:error>', views.catalog, name='catalog'),
    path('catalog', views.catalog, name='catalog'),
    path('user_items/<str:error>', views.user_items, name='user_items'),
    path('user_items', views.user_items, name='user_items'),
    path('add_item', views.add_item, name='add_item'),
    path('buy_item', views.buy_item, name='buy_item'),
    path('remove_item', views.remove_item, name='remove_item')
]

martistupe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

#redirection when not found
from django.views.generic import RedirectView


def handler404(request,exception):
    return HttpResponseRedirect(reverse("manager:index"))

#icon
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('analytics/', include('analytics.urls')),
    path('community/', include('community.urls')),
    path('manager/', include('manager.urls')),
    path('market/', include('market.urls')),
    path('', include('user.urls'))
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'user'
urlpatterns = [
    path('execute_login/', views.execute_login, name='enter'),
    path('registration/', views.registration, name='registration'),
    path('execute_registration/', views.execute_registration, name='complete'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.user_login, name='login')
]

templates/base.html
<!DOCTYPE html>
{% comment %}
 Base template for all apps
{% endcomment %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
     <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
        {% block theme_css %} {% endblock %}
        {% block head %}{% endblock %}
 </head>
 <body>
    <header>
        <title>{% block title %} {% endblock %}</title>
        {% block header %} {% endblock %}
    </header>
 {% block body %}{% endblock %}
 {% block error %}{% endblock %}
 {% block content %}{% endblock %}
 <footer>
        {% block footer %}{% endblock %}
 </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% block theme_js %} {% endblock %}
    {% block my_jquery %}{% endblock %}
    {% block my_js %}{% endblock %}
  </body>
</html>

templates/main_site.html
{% extends "base.html" %}
{% comment %}
 Base template for market app
{% endcomment %}

<!-- Template CSS code -->
{% block theme_css %}
{% load static %}
<meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'shop_theme/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shop_theme/css/style.css' %}" type="text/css">

{% endblock %}

<!-- Navigation bar -->
{% block body %}
 <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

<!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="#"><img src="" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><i class="fa fa-shopping-bag"></i></li>
            </ul>
            <div class="header__cart__price">Credits: <span>{{balance.balance}}</span></div>
            <div class="log_out_link"><a href="{% url 'user:logout' %}">Log out</a></div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
                                    <ul>
                            <li><a href="{% url 'manager:index' %}">Home</a></li>
                            <li><a href="{% url 'market:index' %}">Market</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'market:catalog' %}">Explore catalog</a></li>
                                    <li><a href="{% url 'market:insert' %}">Insert new item</a></li>
                                    <li><a href="{% url 'market:user_items' %}">Check your items</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'analytics:index' %}">Analytics</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'analytics:history' %}">Your history</a></li>
                                    <li><a href="{% url 'analytics:search' %}">Price tracker</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'community:index' %}">Community</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'community:leaderboard' %}">Leaderboard</a></li>
                                    <li><a href="{% url 'community:search' %}">Search user</a></li>
                                    <li><a href="{% url 'community:community_profile' username=request.user %}">My profile</a></li>
                                </ul>
                            </li>
                        </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
    </div>
    <!-- Humberger End -->



    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <img height=60px src="{% static 'shop_theme/img/my_logo.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li {% block manager_active %} {% endblock %}><a href="{% url 'manager:index' %}">Home</a></li>
                            <li {% block market_active %} {% endblock %}><a href="{% url 'market:index' %}">Market</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'market:catalog' %}">Explore catalog</a></li>
                                    <li><a href="{% url 'market:insert' %}">Insert new item</a></li>
                                    <li><a href="{% url 'market:user_items' %}">Check your items</a></li>
                                </ul>
                            </li>
                            <li {% block analytics_active %} {% endblock %}><a href="{% url 'analytics:index' %}">Analytics</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'analytics:history' %}">Your history</a></li>
                                    <li><a href="{% url 'analytics:search' %}">Price tracker</a></li>
                                </ul>
                            </li>
                            <li {% block community_active %} {% endblock %}><a href="{% url 'community:index' %}">Community</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url 'community:leaderboard' %}">Leaderboard</a></li>
                                    <li><a href="{% url 'community:search' %}">Search user</a></li>
                                    <li><a href="{% url 'community:community_profile' username=request.user %}">My profile</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <div class="header__cart__price">
                            <i class="fa fa-shopping-bag"></i>
                            Credits: <span>{{balance.balance}}</span></div>
                        <div class="log_out_link"><a href="{% url 'user:logout' %}">Log out</a></div>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
{% endblock %}

<!-- Template JS code -->
{% block theme_js %}

    <!-- Js Plugins -->
    <script src="{% static 'shop_theme/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'shop_theme/js/mixitup.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'shop_theme/js/main.js' %}"></script>

{% endblock %}

{% block footer %}
<!-- Footer Section Begin -->
<br>
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="" alt=""></a>
                        </div>
                        <ul>
                            <li>CyberDindarolo - TRUST&BUY</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<!-- Footer Section End -->
{% endblock %}